### ISSUE TITLE
linode-launch.py fails - unable to create linodes

### ISSUE THREAD

**Issue by tserlin** [batrick/ceph-linode#26]
I'm unable to create linodes when running the following command:

```
# LINODE_API_KEY=<snip> python ceph-linode/linode-launch.py
...
2018-05-21 18:50:57,867 ERROR list index out of range
Traceback (most recent call last):
  File "ceph-linode/linode-launch.py", line 136, in create
    do_create(*args, **kwargs)
  File "ceph-linode/linode-launch.py", line 54, in do_create
    plan = filter(lambda p: p[u'LABEL'].lower().find(str(machine['plan']).lower()) >= 0, plans)[0]
IndexError: list index out of range
```
This same command worked about 2 months ago.

Note: I'm running this command from another linode, on CentOS 7.

**Comment by tserlin** [comment]
Based on this https://www.linode.com/api/utility/avail.linodeplans , Linode plan labels used to be in the form of "Linode 1024", "Linode 2048", etc.

When I query the API right now, I get "Nanode 1GB", "Linode 2GB", etc.

**Comment by tserlin** [comment]
OK, this works...

Just modify the cluster.json file so that you have lines for the linode plans like:
```
"plan": 2,
"plan": 1,

```
So, "1" for 1GB plan, "2" for 2GB plan, and so on.

**Comment by batrick** [comment]
Well that's aggravating.@tserlin, mind submitting a PR that changes the sample cluster.json?

**Comment by tserlin** [comment]
@batrick 

Here you go: https://github.com/batrick/ceph-linode/pull/27
