### ISSUE TITLE
linodes aren't in same subnet

### ISSUE THREAD

**Issue by bengland2** [batrick/ceph-linode#3]
I fired up an linode cluster with ceph-linode and discovered that the linodes weren't in the same subnet, so ceph-ansible couldn't configure them.   I never saw this before.  Do you have to tell it to create them in the same subnet?

$ ansible -m shell -a 'ifconfig eth0 | awk "/inet /{print $2}"' all

mgr-000 | SUCCESS | rc=0 >>
        inet 173.255.238.79  netmask 255.255.255.0  broadcast 173.255.238.255

client-000 | SUCCESS | rc=0 >>
        inet 66.228.47.20  netmask 255.255.255.0  broadcast 66.228.47.255

osd-001 | SUCCESS | rc=0 >>
        inet 50.116.48.61  netmask 255.255.255.0  broadcast 50.116.48.255

osd-002 | SUCCESS | rc=0 >>
        inet 173.255.230.167  netmask 255.255.255.0  broadcast 173.255.230.255

osd-000 | SUCCESS | rc=0 >>
        inet 69.164.222.67  netmask 255.255.255.0  broadcast 69.164.222.255

mds-000 | SUCCESS | rc=0 >>
        inet 96.126.104.6  netmask 255.255.255.0  broadcast 96.126.104.255

mon-002 | SUCCESS | rc=0 >>
        inet 45.33.65.125  netmask 255.255.255.0  broadcast 45.33.65.255

mon-000 | SUCCESS | rc=0 >>
        inet 66.228.39.50  netmask 255.255.255.0  broadcast 66.228.39.255

mon-001 | SUCCESS | rc=0 >>
        inet 45.33.81.10  netmask 255.255.255.0  broadcast 45.33.81.255

**Comment by batrick** [comment]
> I fired up an linode cluster with ceph-linode and discovered that the linodes weren't in the same subnet, so ceph-ansible couldn't configure them.

What error did you see?

> Do you have to tell it to create them in the same subnet?

They will have the same private subnet. The private IP is added here:

https://github.com/batrick/ceph-linode/blob/master/linode-launch.py#L93

**Comment by bengland2** [comment]
sorry, there are multiple IPs associated with eth0 interface and one of them is the same subnet for all hosts, just getting used to linode after using AWS.  You can close it.
