### ISSUE TITLE
dont want to use upstream Linux kernel 4.17

### ISSUE THREAD

**Issue by bengland2** [batrick/ceph-linode#30]
I want to use whatever kernel boots with GRUB instead of linux kernel 4.17, but I can't figure out how to get linode-launch.py to do that.  Otherwise ceph-ansible will not mount an .iso image (unless I reboot the node!).  Worse yet, I'm not really using  centos7.  Any suggestions?

**Comment by batrick** [comment]
@bengland2 got it working now?

**Comment by bengland2** [comment]
@batrick yes ceph-ansible is working, not sure why it is but losetup now works where before it didn't.  but I still have a very different kernel, 4.17.14 not 3.10, and this somewhat invalidates performance results.  NO easy way that I've found to switch it back to 3.10 kernel, so far manually going into Linode GUI is the only documented way, not fun for 40 linodes.

**Comment by bengland2** [comment]
I tried running python -m pdb linode-launch.py and inspecting the kernels list, I didn't find anything with that label.

**Comment by batrick** [comment]
Ya, it's not listed for some reason. However, you can figure out the kernel id by inspecting the html on linode's website for the dropdown menu where you click the kernel. the "KERNELID" is 210 for "GRUB 2". You can just set that here:

https://github.com/batrick/ceph-linode/blob/master/linode-launch.py#L149

`kernel = 210`

That worked for me.

**Comment by batrick** [comment]
@bengland2 fix in master
