### ISSUE TITLE
hosts file that goes with ansible inventory

### ISSUE THREAD

**Issue by bengland2** [batrick/ceph-linode#34]
I wrote [this script to convert the linode ansible_inventory file to /etc/hosts format](https://github.com/bengland2/ceph-linode/blob/ceph-ansible-stable-31/inventory2hosts.py) so I can just ssh to any node in the inventory, as in "ssh mon-000".  This makes it possible to write scripts that ssh/scp to role in a ceph-linode cluster, like mgr-000, even though the real hostnames change each time you deploy it.  Useful?

**Comment by batrick** [comment]
I'd throw it in scripts/. Feel free to make a PR!

**Comment by bengland2** [comment]
[PR 35 ](https://github.com/batrick/ceph-linode/pull/35)

**Comment by bengland2** [comment]
merged.
