### ISSUE TITLE
would like launch.sh option to just create the linodes and not run ceph-ansible

### ISSUE THREAD

**Issue by bengland2** [batrick/ceph-linode#39]
There are cases where it is desirable to create the linodes but do some additional steps before you run ceph-ansible.   Example: when a new RHCS release comes out, centos doesn't have all the RPMs that it depends on, so you have to insert a repo containing those RPMs before you can install Ceph.  

Suggestion: if the user doesn't specify the --ceph-ansible argument to launch.sh, just have launch.sh skip ceph-ansible and warn the user that they have to do it.    The nice thing about launch.sh is that it's idempotent - if you already created the linodes, then linode-launch.py won't create them again.  But it takes a long time for ceph-ansible to fail so just running launch.sh twice as it is today can be very expensive.  So a user could do something like this:

```
launch.sh
# <make necessary changes to cluster hosts before running ceph-ansible
launch.sh --ceph-ansible /usr/share/ceph-ansible
```
Or they could just run ceph-ansible directly.    If you agree with this, I could submit a PR for it, it's trivial to do.

**Comment by bengland2** [comment]
I'm just faking it for now by creating a dummy ceph-ansible tree with

mkdir -p /tmp/ceph-ansible/roles
touch /tmp/ceph-ansible/site.yml
launch.sh --ceph-ansible /tmp/ceph-ansible

**Comment by batrick** [comment]
This change is cool with me.

**Comment by batrick** [comment]
Think this is obsolete now with the use of cephadm.
