### ISSUE TITLE
Could not re-install ceph after nuke

### ISSUE THREAD

**Issue by kotreshhr** [batrick/ceph-linode#65]
python3 linode.py launch
do_playbook cephadm.yml
python3 linode.py nuke
do_playbook cephadm.yml

throws below errors:
Using /etc/ansible/ansible.cfg as config file
[WARNING]: Unable to parse /root/ceph-linode/ansible_inventory as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

PLAY [all] **********************************************************************************************************
skipping: no hosts matched

PLAY [all] **********************************************************************************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: mdss

PLAY [mdss] *********************************************************************************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: osds

PLAY [osds] *********************************************************************************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: mons

PLAY [mons] *********************************************************************************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: clients

PLAY [clients] ******************************************************************************************************
skipping: no hosts matched

PLAY [all] **********************************************************************************************************
skipping: no hosts matched

PLAY [all] **********************************************************************************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: mon-000

PLAY [mon-000] ******************************************************************************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: mgrs
[WARNING]: Could not match supplied host pattern, ignoring: grafana-servers

PLAY [mons mgrs osds mdss grafana-servers] **************************************************************************
skipping: no hosts matched

PLAY [mon-000] ******************************************************************************************************
skipping: no hosts matched

PLAY [all] **********************************************************************************************************
skipping: no hosts matched

PLAY [clients] ******************************************************************************************************
skipping: no hosts matched

PLAY RECAP **********************************************************************************************************

**Comment by batrick** [comment]
After nuking the VMs disks/settings are completely wiped. You need to redeploy configs/disks using `python3 linode.py launch`. The nice thing here is that it's smart enough to reuse the VMs that are sitting idle. That way you don't create billing events for destroy/create needlessly.
